baseurl: ''
permalink: pretty
title: 'HSC-Bench'
description: 'A unified benchmark for service recommendation and service composition.'
url: ''

logo:
  mobile: 'images/logo/logo-mobile.svg'
  mobile_height: '36px'
  mobile_width: '36px'
  desktop: 'images/logo/logo.svg'
  desktop_height: '36px'
  desktop_width: '170px'

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - netlify.toml
